export const ActionConstants={
    CHANGE_DATE:"CHANGE_DATE",
    CHANGE_TITLE:"CHANGE_TITLE",
    CHANGE_AMOUNT:"CHANGE_AMOUNT",
    SUBMIT_OBJ:"SUBMIT_OBJ",
    CLEAROBJ:"CLEAROBJ",
    UPDATE_TITLE:"UPDATE_TITLE",
    DELETE_RECORD:"DELETE_RECORD",
    TYPE_UPDATE:"TYPE_UPDATE",
    UPDATE_BASIC:"UPDATE_BASIC",
    UPDATE_LUXURY:"UPDATE_LUXURY",
    UPDATE_SELF:"UPDATE_SELF",
    UPDATE_TOTAL:"UPDATE_TOTAL",
    UPDATE_UNDEF:"UPDATE_UNDEF",
    UPDATE_ALL:"UPDATE_ALL",

}